package utp.misiontic2022.c2.p47.reto4.vista;

import java.sql.SQLException;
import java.util.ArrayList;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import utp.misiontic2022.c2.p47.reto4.controlador.ControladorRequerimientos;
import utp.misiontic2022.c2.p47.reto4.modelo.dao.LiderDao;
import utp.misiontic2022.c2.p47.reto4.modelo.vo.Cargo_Salario;
import utp.misiontic2022.c2.p47.reto4.modelo.vo.Lider;
import utp.misiontic2022.c2.p47.reto4.modelo.vo.Suma_Salario;
import utp.misiontic2022.c2.p47.reto4.modelo.vo.Transformar_Nombre;
import utp.misiontic2022.c2.p47.reto4.vista.PrimeraConsulta;
import utp.misiontic2022.c2.p47.reto4.vista.SegundaConsulta;
import utp.misiontic2022.c2.p47.reto4.vista.TerceraConsulta;
import utp.misiontic2022.c2.p47.reto4.vista.CuartaConsulta;

/**
 *
 * @author Alex
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    public static final ControladorRequerimientos controlador = new ControladorRequerimientos();
    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SQLite MisionTic");
        setAlwaysOnTop(false);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 204));
        setName("SQLite"); // NOI18N
        setResizable(false);

        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("Realizar Consulta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Consultas Guardadas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SQLite Script  ");
        jLabel1.setToolTipText("");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido a la interfaz de Consultas de bases de datos  de MisionTic, Proyecto de vivienda del gobierno.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(172, 172, 172))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(21, 21, 21)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(24, 24, 24))
        );
        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Consulta = jTextPane1.getText();
        try {
            if(Consulta.contains("Segundo_Apellido = 'Ortiz'")||Consulta.contains("Segundo_Apellido= 'Ortiz'")||Consulta.contains("Segundo_Apellido ='Ortiz'")||Consulta.contains("Segundo_Apellido  =  'Ortiz'")||Consulta.contains("Segundo_Apellido =  'Ortiz'")||Consulta.contains("Segundo_Apellido  = 'Ortiz'")){
                
                PrimeraConsulta primera = new PrimeraConsulta();
                
                this.setVisible(false);
               // primera.setVisible(true); 
                
           ArrayList<Lider> resultado = controlador.consultarRequerimiento1(Consulta);
            for (Lider lider:resultado){
                System.out.print(lider.getNombre()+" ");
                System.out.print(lider.getPrimer_Apellido()+" ");
                System.out.print(lider.getSegundo_Apellido()+" ");
                System.out.println(lider.getSalario());
                 
            }
            Object [][] lista= new Object[resultado.size()][4];
            for(int i = 0; i < resultado.size();i++){
                lista[i][0]=resultado.get(i).getNombre();
                lista[i][1]=resultado.get(i).getPrimer_Apellido();
                lista[i][2]=resultado.get(i).getSegundo_Apellido();
                lista[i][3]=resultado.get(i).getSalario();
            }
            
            primera.jTable1.setModel(new javax.swing.table.DefaultTableModel(
                lista,
                new String [] {
                    "          Nombre", "     Primer Apellido", "   Segundo Apellido", "          Salario"
                }
            )); 
            primera.setVisible(true);  

           
        }else if(Consulta.contains("LOWER(SUBSTR(Nombre,1,1)) || UPPER(SUBSTR(Nombre,2,LENGTH(Nombre)))")||Consulta.contains("lower(substr(Nombre,1,1)) || upper(substr(Nombre,2,length(Nombre)))")||Consulta.contains("Lower(Substr(Nombre,1,1)) || Upper(Substr(Nombre,2,Length(Nombre)))")||Consulta.contains("LOWER(SUBSTR(Nombre,1,1))||UPPER(SUBSTR(Nombre,2,LENGTH(Nombre)))")||Consulta.contains("lower(substr(Nombre,1,1))||upper(substr(Nombre,2,length(Nombre)))")||Consulta.contains("Lower(Substr(Nombre,1,1))||Upper(Substr(Nombre,2,Length(Nombre)))")){
            SegundaConsulta segunda = new SegundaConsulta();
            this.setVisible(false);
            ArrayList<Transformar_Nombre> resultado = controlador.consultarRequerimiento2(Consulta);
            for (Transformar_Nombre transformar:resultado){
                System.out.println(transformar.getTransformar());
            }
            Object [][] lista= new Object[resultado.size()][1];
            for(int i = 0; i < resultado.size();i++){
                lista[i][0]=resultado.get(i).getTransformar();
            }
            
            segunda.jTable1.setModel(new javax.swing.table.DefaultTableModel(
                lista,
                new String [] {
                    "             Nombre"
                }
            )); 
            segunda.setVisible(true); 
        }else if(Consulta.contains("sum(Salario)")||Consulta.contains("Sum(Salario)")||Consulta.contains("SUM(Salario)")){
            CuartaConsulta cuarta = new CuartaConsulta();
            this.setVisible(false);
            //cuarta.setVisible(true);
            ArrayList<Suma_Salario> resultado = controlador.consultarRequerimiento3(Consulta);
            for (Suma_Salario Suma:resultado){
                System.out.print(Suma.getCiudad()+" ");
                System.out.println(Suma.getSumaSalario());
            }
            Object [][] lista= new Object[resultado.size()][2];
            for(int i = 0; i < resultado.size();i++){
                lista[i][0]=resultado.get(i).getCiudad();
                lista[i][1]=resultado.get(i).getSumaSalario();
            }
            
            cuarta.jTable1.setModel(new javax.swing.table.DefaultTableModel(
                lista,
                new String [] {
                    "           Ciudad de Residencia", "                  Suma de Salarios"
                }
            )); 
            cuarta.setVisible(true);
        }else if(Consulta.contains("avg(Salario)")||Consulta.contains("Avg(Salario)")||Consulta.contains("AVG(Salario)")){
            TerceraConsulta tercera = new TerceraConsulta();
            this.setVisible(false);
            //tercera.setVisible(true);
            ArrayList<Cargo_Salario> resultado = controlador.consultarRequerimiento4(Consulta);
            for (Cargo_Salario Carsalario:resultado){
                System.out.print(Carsalario.getCargo()+" ");
                System.out.println(Carsalario.getSalario());
            }
            Object [][] lista= new Object[resultado.size()][2];
            for(int i = 0; i < resultado.size();i++){
                lista[i][0]=resultado.get(i).getCargo();
                lista[i][1]=resultado.get(i).getSalario();
            }
            
            tercera.jTable1.setModel(new javax.swing.table.DefaultTableModel(
                lista,
                new String [] {
                    "                    Cargo", "                   Salario"
                }
            )); 
            tercera.setVisible(true);
        }else{

            JOptionPane.showMessageDialog(null, "¡ERROR!\nConsulta invalida");
            jTextPane1.setText(null);
            

        }
            
        } catch (Exception e) {
            System.err.println(e);
        }
        
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Consulta = jTextPane1.getText();
        lista1.add(Consulta);
        int resul = JOptionPane.showConfirmDialog(null, "¿Deseas ver los resultados de su consulta?", "Error", JOptionPane.YES_NO_OPTION);
        if (resul ==0){
            jTextPane1.setText(Consulta);
        }else{
            jTextPane1.setText(null);
        }
        
        
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
    try {
        Consultas primera = new Consultas();
        if(lista1 == null || lista1.size() == 0){
            int resul = JOptionPane.showConfirmDialog(null, "!No existen consultas del proyecto de vivienda!\n¿Deseas realizar consultas al proyecto?", "Error", JOptionPane.YES_NO_OPTION);
            if (resul ==0){
                this.setVisible(true);
            }else{
                System.exit(0);
            }
        }else{
            for (int i=0; i<=4; i++){
                 if(lista1.get(i).contains("Segundo_Apellido = 'Ortiz'")||lista1.get(i).contains("Segundo_Apellido= 'Ortiz'")||lista1.get(i).contains("Segundo_Apellido ='Ortiz'")||lista1.get(i).contains("Segundo_Apellido  =  'Ortiz'")||lista1.get(i).contains("Segundo_Apellido =  'Ortiz'")||lista1.get(i).contains("Segundo_Apellido  = 'Ortiz'")){
                    
                
                
                this.setVisible(false);
               // primera.setVisible(true); 
                
                ArrayList<Lider> resultado;
                resultado = controlador.consultarRequerimiento1(lista1.get(i));
                Object [][] lista= new Object[resultado.size()][4];
                for(int j = 0; j < resultado.size();j++){
                     lista[j][0]=resultado.get(j).getNombre();
                     lista[j][1]=resultado.get(j).getPrimer_Apellido();
                     lista[j][2]=resultado.get(j).getSegundo_Apellido();
                     lista[j][3]=resultado.get(j).getSalario();
                 }
        
                primera. jTable1.setModel(new javax.swing.table.DefaultTableModel(
                lista,
                 new String [] {
                   "              Nombre", "      Primer Apellido", "     Segundo Apellido", "                  Salario"
                 }
                )); 
                primera.setVisible(true);  
            }else if(lista1.get(i).contains("LOWER(SUBSTR(Nombre,1,1)) || UPPER(SUBSTR(Nombre,2,LENGTH(Nombre)))")||lista1.get(i).contains("lower(substr(Nombre,1,1)) || upper(substr(Nombre,2,length(Nombre)))")||lista1.get(i).contains("Lower(Substr(Nombre,1,1)) || Upper(Substr(Nombre,2,Length(Nombre)))")||lista1.get(i).contains("LOWER(SUBSTR(Nombre,1,1))||UPPER(SUBSTR(Nombre,2,LENGTH(Nombre)))")||lista1.get(i).contains("lower(substr(Nombre,1,1))||upper(substr(Nombre,2,length(Nombre)))")||lista1.get(i).contains("Lower(Substr(Nombre,1,1))||Upper(Substr(Nombre,2,Length(Nombre)))")){
               
                this.setVisible(false);
                ArrayList<Transformar_Nombre> resultado = controlador.consultarRequerimiento2(lista1.get(i));
                Object [][] lista= new Object[resultado.size()][1];
                for(int j = 0; j < resultado.size();j++){
                    lista[j][0]=resultado.get(j).getTransformar();
                }
                
                primera.jTable3.setModel(new javax.swing.table.DefaultTableModel(
                    lista,
                    new String [] {
                        "                     Nombre"
                    }
                )); 
                primera.setVisible(true); 
            }else if(lista1.get(i).contains("sum(Salario)")||lista1.get(i).contains("Sum(Salario)")||lista1.get(i).contains("SUM(Salario)")){
                
                this.setVisible(false);
                ArrayList<Suma_Salario> resultado = controlador.consultarRequerimiento3(lista1.get(i));
                Object [][] lista= new Object[resultado.size()][2];
                for(int j = 0; j < resultado.size();j++){
                    lista[j][0]=resultado.get(j).getCiudad();
                    lista[j][1]=resultado.get(j).getSumaSalario();
                }
                
                primera.jTable4.setModel(new javax.swing.table.DefaultTableModel(
                    lista,
                    new String [] {
                        "                Ciudad de Residencia", "                Suma de Salarios"
                    }
                )); 
                primera.setVisible(true);
            }else if(lista1.get(i).contains("avg(Salario)")||lista1.get(i).contains("Avg(Salario)")||lista1.get(i).contains("AVG(Salario)")){
                this.setVisible(false);
                ArrayList<Cargo_Salario> resultado = controlador.consultarRequerimiento4(lista1.get(i));
                Object [][] lista= new Object[resultado.size()][2];
                for(int j = 0; j < resultado.size();j++){
                    lista[j][0]=resultado.get(j).getCargo();
                    lista[j][1]=resultado.get(j).getSalario();
                }
                
                primera.jTable5.setModel(new javax.swing.table.DefaultTableModel(
                    lista,
                    new String [] {
                        "                           Cargo", "                   Promedio de Salarios"
                    }
                )); 
                primera.setVisible(true);
            }else{
                int resul = JOptionPane.showConfirmDialog(null, "!Hay un error en una de las consultas guardadas!\n¿Deseas guardar una consulta nueva?", "Error", JOptionPane.YES_NO_OPTION);
                if (resul ==0){
                    this.setVisible(true);
                }else{
                    primera.setVisible(true);
                }
                

            }
        }
     } }catch (SQLException e) {
        e.printStackTrace();
     }   
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private ArrayList<String> lista1 = new ArrayList<String>();
    // End of variables declaration//GEN-END:variables
}
